run_nfcore_demo: false
general:
  wf_opts: '-resume -ansi-log false'
demo:
  wf_opts: '-profile test,singularity'
fetchngs:
  wf_opts: '-profile test,singularity -r dev --nf_core_pipeline rnaseq'
rnaseq:
  wf_opts: '-profile test,singularity'
