workflows: 'fetchngs,rnaseq'
general:
  wf_opts: '-resume -ansi-log false'
demo:
  wf_opts: '-profile test,docker'
  add_config: 'configs/multiqc.config'
fetchngs:
  wf_opts: '-profile test,docker -r dev --nf_core_pipeline rnaseq'
  add_config: 'configs/multiqc.config'
rnaseq:
  wf_opts: '-profile test,docker'
  add_config: 'configs/multiqc.config'
